/*
 * generated by Xtext 2.23.0
 */
package be.unamur.polystore;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PmlRuntimeModule extends AbstractPmlRuntimeModule {
}
