/*
 * generated by Xtext 2.23.0
 */
package be.unamur.polystore.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class PmlProposalProvider extends AbstractPmlProposalProvider {
}
