/*
 * generated by Xtext 2.23.0
 */
package be.unamur.polystore.validation;

import org.eclipse.xtext.validation.Check;

import be.unamur.polystore.pml.AbstractMappingRule;
import be.unamur.polystore.pml.Edge;
import be.unamur.polystore.pml.EntityMappingRule;
import be.unamur.polystore.pml.EntityType;
import be.unamur.polystore.pml.MappingRules;
import be.unamur.polystore.pml.PhysicalField;
import be.unamur.polystore.pml.PmlPackage;
import be.unamur.polystore.pml.RelationshipType;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PmlValidator extends AbstractPmlValidator {
	
	public static final String INVALID_NAME = "invalidName";
	public static final String INVALID_ERULE = "invalidEntityMappingRule";

	@Check
	public void checkEntityStartsWithCapital(EntityType entity) {
		if (!Character.isUpperCase(entity.getName().charAt(0))) {
			warning("Name should start with a capital",
					PmlPackage.Literals.ENTITY_TYPE__NAME,
					INVALID_NAME);
		}
	}
	
	@Check
	public void checkRelationshipStartsWithLowerCase(RelationshipType relationship) {
		if (!Character.isLowerCase(relationship.getName().charAt(0))) {
			warning("Relationhsip names should start with a lower case letter",
					PmlPackage.Literals.RELATIONSHIP_TYPE__NAME,
					INVALID_NAME);
		}
	}
	
	@Check void checkCapitalLettersForEdge(Edge edge) {
		for(char c : edge.getName().toCharArray()) {
			if(!Character.isUpperCase(c) && Character.isAlphabetic(c))
				warning("Edges name should be full capital letters", PmlPackage.Literals.ABSTRACT_PHYSICAL_STRUCTURE__NAME,INVALID_NAME);
		}
	}
	
	@Check void checkAttributeVsFieldInEntityMappingRule(EntityMappingRule rule) {
		if(rule.getAttributesConceptual().size()!= rule.getPhysicalFields().size()) {
			error("Number of conceptual attributes and physical fields in entity mapping rule should be equal", PmlPackage.Literals.ENTITY_MAPPING_RULE__ENTITY_CONCEPTUAL, INVALID_ERULE);
			error("Number of conceptual attributes and physical fields in entity mapping rule should be equal", PmlPackage.Literals.ENTITY_MAPPING_RULE__PHYSICAL_STRUCTURE, INVALID_ERULE);
		}
	}
	
	@Check void checkFieldIsMapped(PhysicalField field, MappingRules rules) {
		boolean mapped = false;
		for(AbstractMappingRule rule : rules.getMappingRules()) {
			if(rule instanceof EntityMappingRule) {
				if(((EntityMappingRule) rule).getPhysicalFields().contains(field)) {
					mapped = true;
					break;
				}
			}
		}
		if(!mapped) {
		}
	}
	
}
