/*
 * generated by Xtext 2.23.0
 */
package be.unamur.polystore.ide;

import be.unamur.polystore.PmlRuntimeModule;
import be.unamur.polystore.PmlStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PmlIdeSetup extends PmlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PmlRuntimeModule(), new PmlIdeModule()));
	}
	
}
