/*
 * generated by Xtext 2.23.0
 */
package be.unamur.polystore;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PmlStandaloneSetup extends PmlStandaloneSetupGenerated {

	public static void doSetup() {
		new PmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
