/*
 * generated by Xtext 2.23.0
 */
package be.unamur.polystore.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PmlUiModule extends AbstractPmlUiModule {

	public PmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
